spring.application.name=Image-to-webp-converate
server.port=8080
# Configuration for the application
spring.main.allow-bean-definition-overriding=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
